name: Run tele_bot.py

on:
  schedule:
    - cron: '30 22 * * *'  # Runs every day at 22:30 UTC (06:30 SGT)
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot python-dotenv selenium pandas openpyxl aiohttp asyncio webdriver_manager DateTime

    - name: Install Chrome and ChromeDriver
      run: |
        # Update package lists
        sudo apt-get update
        
        # Install required dependencies
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
        
        # Add Google Chrome's signing key and repository
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        
        # Install the latest stable version of Google Chrome
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
        # Download and install the latest stable version of ChromeDriver
        LATEST_CHROMEDRIVER=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Run tele_bot.py
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        USER: ${{ secrets.USER }}
        PW: ${{ secrets.PW }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        max_retries=3
        counter=0
        until [ $counter -ge $max_retries ]
        do
          python tele_bot.py && break || counter=$((counter+1))
          echo "Attempt $counter failed. Retrying in 10 seconds..."
          sleep 10
        done
        if [ $counter -eq $max_retries ]; then
          echo "All attempts failed. Exiting."
          exit 1
        fi
